(async () => {
  const modules = await (await fetch('https://raw.githubusercontent.com/powercord-org/powercord/v2/src/fake_node_modules/powercord/webpack/modules.json')).json();
  console.log('\n  // Auto generated by script');
  console.log(Object.keys(modules).reduce((acc, x) => acc += `  ${x}: goosemod.webpackModules.findByProps(${modules[x].map(y => `'${y}'`).join(', ')}),\n`, ''));
})();